<form class="form-horizontal form-box" action="/user/signup" method="post">
	<h4 class="form-box-header">Sign up</h4>
	<div class="form-box-content">


		<div class="control-group">
			<label class="control-label">Username</label>
			<div class="controls">
				<input  data-placement="right" type="text" name="username">
			</div>
		</div>

		<div class="control-group">
			<label class="control-label">Password</label>
			<div class="controls">
				<input  data-placement="right" type="password" name="password">
			</div>
		</div>

		<div class="control-group">
			<label class="control-label">Retype Password</label>
			<div class="controls">
				<input  data-placement="right" type="password" name="retype">
			</div>
		</div>

		<div class="form-actions">
			<button class="btn btn-success"><i class="icon-save"></i> Sign up </button>
		</div>

	</div>
</form>